# fly.toml app configuration file generated for rbp-rod-builder-pro-staging on 2025-08-19T22:12:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rbp-rod-builder-pro-staging'
primary_region = "sea"

[mounts]
  source="data"
  destination="/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/ping"
