# <!-- BEGIN RBP GENERATED: hq-skeleton-v0-1 -->
name = "RBP HQ Admin"
client_id = "REPLACE_WITH_HQ_APP_CLIENT_ID"
application_url = "http://localhost:3002"
embedded = true

[auth]
redirect_urls = ["http://localhost:3002/auth/callback"]

[webhooks]
api_version = "2025-01"

[app_proxy]
url = "https://example.test"
subpath = "hq-admin"
prefix = "/apps"
# <!-- END RBP GENERATED: hq-skeleton-v0-1 -->
