name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# <!-- BEGIN ci-starter-green-v1 -->
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies (workspace)
        run: pnpm -w install --frozen-lockfile

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile
      - name: Run workspace tests if present
        run: pnpm -w -r run --if-present test

  smoke_admin_mock:
    name: smoke_admin_mock
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ hashFiles('src/apps/admin.portal/**') != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile
      - name: Run admin smoke (mock) if present
        run: pnpm -w run --if-present smoke:admin:mock
# <!-- END ci-starter-green-v1 -->