# <!-- BEGIN RBP GENERATED: github-preflight -->
name: Preflight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Preflight (strict)
        run: pnpm preflight:strict
# <!-- END RBP GENERATED: github-preflight -->
